#!/usr/bin/env python
import itertools
import math
import optparse
import random
import sys
import bleu
import math
from collections import namedtuple, Counter

optparser = optparse.OptionParser()
optparser.add_option("-r", "--reference", dest="reference", default="data/train.en",
                     help="English reference sentences")
optparser.add_option("-n", "--nbest", dest="nbest", default="data/train.final",
                     help="N-best lists")
optparser.add_option("-b", "--bleu", dest="actual", default="data/train.actual",
                     help="file to write to")

(opts,_) = optparser.parse_args()
ref = [line.strip().split() for line in open(opts.reference)]

ptr = open(opts.actual, 'w')
sys.stderr.write("Reading N-best lists...")
nbests = [[] for _ in ref]
for n, line in enumerate(open(opts.nbest)):
  (i, sentence, features) = line.strip().split("|||")
  (i, features) = (int(i), [float(h) for h in features.strip().split()])
  stats = tuple(bleu.bleu_stats(sentence.strip().split(), ref[i]))
  b = bleu.smoothed_bleu(stats)
  ptr.write(str(b) + '\n')
  if n % 2000 == 0:
    sys.stderr.write(".")
sys.stderr.write("\n")
ptr.close()
