#!/usr/bin/env python
import optparse
import sys
import pickle
from sklearn.preprocessing import StandardScaler
from collections import namedtuple

optparser = optparse.OptionParser()
optparser.add_option("-n", "--nbest", dest="nbest", default="data/test.final",
                     help="N-best file")
optparser.add_option("-p", "--pickle_file", dest="pickle", default="sgd_trainer.pickle",
                     help="pickle file created by learn, with scaler for features")
(opts, _) = optparser.parse_args()

ptr = open(opts.pickle)
(scaler, sgd) = pickle.load(ptr)
ptr.close()

translation = namedtuple("translation", "english, features")
nbests = []
for line in open(opts.nbest):
  (i, sentence, features) = line.strip().split("|||")
  if len(nbests) <= int(i):
    nbests.append([])
  features = [float(h) for h in features.strip().split()]
  features = features[:10] + features[12:16] + features[18:]
  nbests[int(i)].append(translation(sentence.strip(), features))

for nbest in nbests:
  top = nbest[0]
  for i in range(5):
    for translation in nbest:
      diff = [c1j-c2j for c1j,c2j in zip(translation.features, top.features)]
      c = sgd.predict(scaler.transform(diff))
      if c == 1: top = translation
  print top.english

